services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: gis-oms-xml
    env_file:
      - .env
    environment:
      - TZ=Europe/Moscow
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - ./logs:/app/logs
      - ./debug:/app/debug
