services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: gis-oms-xml
    env_file:
      - .env
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
      - ./logs:/app/logs
